imports:
    - { resource: ivory_ck_editor.yml }
    - { resource: sonata_admin.yml }
    - { resource: sonata_doctrine_orm_admin.yml }
    - { resource: sonata_block.yml }
    - { resource: sonata_formatter.yml }
    - { resource: sonata_classification.yml }
    - { resource: sonata_media.yml }
    - { resource: sonata_user.yml }
    - { resource: sonata_news.yml }
    - { resource: sonata_cache.yml }

sonata_core:
    form:
        mapping:
            enabled: false
